#import <React/RCTBridgeModule.h>
#import <React/RCTEventEmitter.h>

// The Swift header is auto-generated by Xcode for @objc-annotated Swift classes.
// This .m file registers the Swift module with the React Native runtime.

@interface RCT_EXTERN_MODULE(WifiScanModule, RCTEventEmitter)

RCT_EXTERN_METHOD(requestPermissions:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(startScan:(nonnull NSNumber *)scanIntervalMs
                  rssiThreshold:(nonnull NSNumber *)rssiThreshold)

RCT_EXTERN_METHOD(stopScan)

RCT_EXTERN_METHOD(connectToNetwork:(NSString *)ssid
                  password:(NSString *)password
                  resolver:(RCTPromiseResolveBlock)resolve
                  rejecter:(RCTPromiseRejectBlock)reject)

RCT_EXTERN_METHOD(disconnect)

@end
